### ISSUE TITLE
Themed Menu

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-FW#219]
Make a themed menu that looks like this:

![image](https://github.com/AEFeinstein/Super-2024-Swadge-FW/assets/231180/42aaf7a6-967a-45da-a543-fca653210c8f)

The fonts are Righteous with a 150% vertical stretch and Rodin Pro Extra Black

### TODO

- [ ] Animate the background
- [ ] Offset text from parallelograms & outline it
- [ ] Fix battery indicator placement
- [ ] Clean up fonts
    - [ ] Fix vertical font offsets
- [ ] LED Effects

**Comment by AEFeinstein** [comment]
Progress in https://github.com/AEFeinstein/Super-2024-Swadge-FW/tree/theme-menu

TODO

- [ ] Animate the background
- [ ] Offset text from parallelograms & outline it
- [ ] Fix battery indicator placement
- [ ] Clean up fonts
    - [ ] Fix vertical font offsets
- [ ] LED Effects
