### ISSUE TITLE
MIDI Support

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2024-Swadge-FW#230]
**Summary**
This feature is about turning the swadge into a real MIDI synthesizer! This would mean, at a minimum, being able to use the swadge as a USB MIDI synth, and playing back MIDI files loaded into the firmware. The implementation would be targeted at implementing [General MIDI](https://en.wikipedia.org/wiki/General_MIDI) to whatever extent is feasible.

**Implementation Plan**
The initial implementation can be very basic, as a proof of concept. TinyUSB comes with MIDI Streaming support, so the first step is to add the descriptors and pull that into a mode. Then, we ignore everything except the`NOTE ON/OFF` messages, and play those using the simple waves that are already supported.

The next step would be creating a way to define an instrument to be synthesized. This is the area where we'd have the most freedom with the implementation, so we could start out with something very basic here too: pick a waveform and define an envelope. Once the rest of the MIDI player is fully implemented at a basic level, we can just go wild making the instruments fancier until we run out of time or CPU, or we end up with a full-blown programmable synthesizer. Some less-than-basic things to do here after the initial implementation would be adding low-frequency oscillators and filters without supporting totally arbitrary synth pipelines.

As for the instruments themselves, General MIDI specifies 128 specific instruments (apparently this is the culprit behind every keyboard ever having helicopter sounds, phone rings, and whatever a "Goblins" is), so coming up with definitions for all of these might not really be feasible, but we could probably get a decent number of them, especially if we make it easy for anyone to define an instrument voice with a simple config file or something like that. I assume you can probably export these from actual synth software? Also note that we can come up with our own instruments and define them in a separate "program bank" from the ones General MIDI supports, so we can fix the glaring omission of Cat Meow from the spec.

Along with the instruments, we would create the MIDI player which is responsible for actually "playing" the instruments with a bank of software synths, mixing them together, applying more filters, etc. This would be used directly by the USB MIDI mode, or controlled by an equivalent to the current Song Player when playing a MIDI file. The initial implementation of this could just control a single synth to play songs without any filters, mixing, or polyphony.

After that basic functionality is complete, the rest of the work is basically just improving and expanding the player to meet the General MIDI specs, which would mainly mean:
* 24-voice polyphony
* Pitch bending
* Note velocity
* Sustain pedal signal

Again, all this is keeping in mind that implementing General MIDI seems like a decent goal to shoot for absent any technical limitations, but isn't a hard requirement and there's basically no downside to just partially implementing it.

For a stretch goal after synthesized instruments are working, it'd be nice to support at least one sample-based instrument. Extra cool points if we have a way to record with the swadge mic and then use that as an instrument.

Another thing that's technically possible is piping the audio back to the computer as a USB audio device. Which I guess would be cool if you want to compose swadge music on your computer and record it or play it back on your actual speakers. But you could also just plug the swadge into some headphones or the line in too...

**MIDI Player - Technical Spec**
The MIDI player itself will consist of two parts: the MIDI engine, which is responsible for accepting MIDI commands and synthesizing audio; and the MIDI file parser, which will either read MIDI commands from a MIDI file directly, or generate them from some equivalent structure, and send them to the MIDI engine for playback.

**Resources**
* USB MIDI 1.0 Specification: https://www.usb.org/sites/default/files/midi10.pdf
* A super basic page on the basic MIDI commands: https://computermusicresource.com/MIDI.Commands.html
* Arduino MIDI synth project, which implements all the complicated synth stuff and is MIT licensed: https://github.com/DLehenbauer/arduino-midi-sound-module
* Another Arduino MIDI Synth project, specifically for ESP32: https://github.com/esp32beans/ESP32USBMIDI

============

**To-do List**

Not necessarily planning to get to all of these but this is everything I can think of that wouldn't be totally crazy to support.

MIDI commands:
- [x] Note on/off
- [x] Afterpressure
- [x] All notes off
- [x] All sounds off (Panic Button)
- [x] Program select
- [x] Pitch bend
- [x] Set tempo
- [ ] Reset
- [ ] Active Sense (stop playing if not received for >300ms)
- [ ] Mono Operation
- [ ] Poly Operation
- [ ] Omni on/off (do/don't listen to all 16 channels)
- [x] Control: Hold (sustain) pedal
- [x] Control: Sustenuto pedal
- [ ] Control: Legato pedal
- [ ] Control: Hold 2 (increase release time)
- [x] Control: Channel volume
- [x] Control: Release
- [x] Control: Attack
- [x] Control: Sustain Volume (CC# 76)
- [x] Control: Decay (CC# 75)
- [x] Control: Chorus level
- [ ] Control: Tremolo
- [ ] Control: Vibrato (Modulation Wheel)
- [ ] Control: Reverb
- [ ] Control: Registered Parameter: Pitch bend range
- [ ] Control: General Purpose Sliders (maybe for LEDs?)
- [ ] Control: Loop points using custom controllers as defined [here](https://www.reddit.com/r/FL_Studio/comments/33uco5/comment/cqp7v2z/) or using a similar convention (several exist)
- [x] Universal SysEx: General MIDI Enable/Disable
- [ ] Universal SysEx: Master Volume

MIDI engine:
- [X] Wavetable instrument playback
- [x] Percussion instrument playback (via callback)
- [x] Sampled instrument playback
- [ ] Sampled instruments - respect ADSR
- [ ] Sampled instruments - loop points for sustain
- [X] Polyphony per-channel
- [X] Reserved percussion polyphony
- [x] Channel-independent polyphony (e.g. 24 voices pooled across all channels)
- [x] Intelligent note stealing if all voices are in use
- [ ] Handle note off when multiple of the same note are playing (stop either first or last played note)
- [x] Handle special cases for percussion note on/off (hi-hats and whistles)
- [x] ADSR envelopes

MIDI file parser:
- [x] Type 0 (single-track) file support
- [x] Type 1 (multi-track, simultaneous -- most common) file support
- [x] Type 2 (multi-track, in sequence) file support*
- [x] Basic commands
- [x] Timecode / time signature parsing & calculation
- [x] Running status handling
- [x] Text (text, track name, instrument name, lyrics, section, etc.)
- [ ] Tempo map creation on file load

MIDI Utilities:
- [ ] A reusable "lookahead" player/parser mode that can be used to grab MIDI events slightly ahead-of-time for rhythm games, etc.

**Comment by AEFeinstein** [comment]
Other resource: http://midi.teragonaudio.com/

**Comment by dylwhich** [comment]
A couple more resources:
* http://www.philrees.co.uk/articles/midimode.htm
* http://blitter.com/~russtopia/MIDI/~jglatt/tech/midispec.htm

**Comment by dylwhich** [comment]
A random thought: it should be possible for the swadge to appear as a USB mass storage device and let the user upload a MIDI file into a fake filesystem in SPIRAM. If it works well, we could even make it usable by other modes for something like uploading a custom level. Or we could use it to make restore/backup a thing. Obviously a MIDI file wouldn't realistically fit in NVS but I think it would still be cool to support user-supplied songs somehow even if it doesn't persist.

**Comment by AEFeinstein** [comment]
That feels just involved enough to be an easter egg

**Comment by AEFeinstein** [comment]
I'm gonna call this done. We still have #299 for efficiency, but I don't think we're adding more core MIDI functionality. @dylwhich, feel free to reopen if I'm off the mark,
