### ISSUE TITLE
Sequencer/tracker

### ISSUE THREAD

**Issue by DeadlySprinklez** [AEFeinstein/Super-2024-Swadge-FW#26]
## Summary
A simple tracker for music creation, live, on the Swadge. BPM modification, two-channel support for chords, and a loop toggle are included.

## Old Technical Spec

- ~~Main screen: D-Pad moves around the timeline and up/down in scale. Touchpad sliding for quick scrubbing. A to place a left-channel note, and B to place a right-channel note. Only one of each note can be on the same beat at the same time - attempting to place another note will move the note instead. Start to play/pause, and Select to toggle into a track modification menu.~~
- ~~Track modification menu: D-Pad Up and Down to select options, D-Pad Left and Right to modify BPM if selected. Start to save, Select to cancel.~~

## New Technical Spec

See https://onlinesequencer.net/ for inspiration

- [x] Full piano (C2 -> C8)
    - [x] Reduce range to what sounds good on speaker
- [x] Cursor moves grid cells
- [x] Selecting a cell toggles the note for it
- [x] Notes are played when placed
- [x] Normal menu options for Song Parameters
    - [x] Tempo
    - [x] Grid lines (whole, half, third, quarter, sixth, eighth, twelfth, sixteenth)
    - [x] Time signature i.e. where thick bar line is drawn on grid (2/4, 3/4, 4/4, 5/4)
    - [x] If the song loops
    - [x] When the song ends
- [x] Normal menu for file operations
    - [x] Save (four files, numbered names)
    - [x] Save As
    - [x] Autosave on quit
    - [x] Load
    - [x] Save and load general settings, init menu with these vals
- [x] Note Parameters - This is a touch wheel menu
    - [x] Instrument Select
        - [x] Actually have this play different instruments
        - [x] Pick a unique set of MIDI instruments
    - [x] Note type select (whole, half, quarter, eighth, sixteenth)

## UI

Deep blue to dark blue gradient background with music sheet-like white lines drawn across the screen. A yellow reticule is visible on the track, shaped like two arrow brackets (< >) which can place notes when the corresponding button is pressed. The notes are a red bubble with a white L, and a light blue bubble with a black R, respectively.

**Mockups**
(To be added)

**How to Test**
If notes are placed and the play button is pressed, the timeline should manifest a playhead and it should scroll from the beginning of the track to the end of the track, playing the notes to the beat when the playhead arrives at them.

**Comment by AEFeinstein** [comment]
@DeadlySprinklez any anything on this?

**Comment by AEFeinstein** [comment]
Putting this off until next year

**Comment by DeadlySprinklez** [comment]
Picking this up again!

**Comment by AEFeinstein** [comment]
Woo!

**Comment by AEFeinstein** [comment]
@DeadlySprinklez let me know on Discord that the week between 9/10 and 9/17 is for evaluation, and we'll check after then if this is feasible, or gets shelved / handed off.
