### ISSUE TITLE
Swadge Hero

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2024-Swadge-FW#288]
# Summary
It's a game, somewhere between DDR and Guitar Hero. It should have at least 10 playable songs with three difficulties each. Notes are mapped to buttons and the touchpad can be a whammy-like input.

# Technical Spec
https://github.com/AEFeinstein/midi-ch can be used to auto-generate chart data from MIDIs
Info on the chart format exported can be found here: https://github.com/TheNathannator/GuitarGame_ChartFormats/blob/main/doc/FileFormats/.chart/Core%20Infrastructure.md
The exported chart is converted by the asset preprocessor into something more binary and swadge-friendly.

# UI
* Normal menu for picking a song, difficulty, etc.
    * Maybe color-shift it?
* Not sure what to do for high score display yet

# Mockups
Nah

# How to Test
Play it! It should feel right, timings are important here.\

# TODO

## Gameplay
- [x] Fail meter (hit is +1, miss is -2)
- [x] Combo Counter
- [x] Scoring
    - [x] Save best score when done
- [ ] ~~Touchpad to pitch bend. Only allow during holds?~~
- [ ] ~~Shake to star power? How to accumulate?~~
- [x] Pause Button
- [x] Investigate letter scoring system
    >  I got a full combo on chowa grove but still scored a B+
- [x] Investigate score saving (incorrect)
    > Also I scored 3654pts but my high score says 1218?
- [x] Fix consistently late input lag

## Graphics
- [x] Replace circle notes with icons
- [x] Add VFX for note hits & misses
- [x] LED FX

## UI
- [x] End of song screen
    - [x] Show score
    - [x] Show progress bar
    - [x] Draw line between 'hit' and 'miss' notes on score screen
- [x] High Score display (build into menu)
- [x] Settings
    - [x] Fail off
    - [x] Note scroll speed
    - [x] ~~Calibration mode?~~

**Comment by AEFeinstein** [comment]
Calibration isn't necessary with timestamped notes

**Comment by AEFeinstein** [comment]
Update Ocean City 1989 title

**Comment by AEFeinstein** [comment]
Might need minor tweaking wrt. song order, but it's shippable!
